CREATE TABLE cases (
	case_pk INT AUTO_INCREMENT PRIMARY KEY,
	case_name VARCHAR(255) NOT NULL,
	case_link VARCHAR(255) NOT NULL,
	summary_link VARCHAR(255) 
);

INSERT INTO cases (`case_name`, `case_link`, `summary_link`)
VALUES
('Juma Hamidu vs The Republic, Criminal Appeal No. 67 of 2001, Court of Appeal',
'http://localhost:8888/miriam_project/cases/JumaHamiduCase.pdf',
'http://localhost:8888/miriam_project/cases/JumaHamiduSummary.pdf'),
('Tatu Bushiri vs Mussa Hamisi, Civil Appeal No. 61 of 2002, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNo61of2002.pdf',
'NULL'),
('NIC (T) Limited vs Abdalla Makunganya, Civil Application N0. 14 of 2003, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNo14of2003.pdf',
'NULL'),
('The Managing Editor, Majira Newspaper And Business Printers Ltd vs Majura Magafu And Peter Swai, Civil Appeal No. 90 of 2003',
'http://localhost:8888/miriam_project/cases/CIVNO90OF2003(2).pdf',
'NULL'),
('Joyce Beda Mpinda vs CRDB Bank Ltd And Another, Gwalogano Abasi Mwasabwite and Erick Auction Mart & Court Broker, Civil Application N0. 181 of 2004, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO181OF2004.pdf',
'NULL'),
('Etieness Hotel vs National Housing Corporation, Civil Reference No. 32 of 2005, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO32OF2005.pdf',
'NULL'),
('D.N Bahram And Co. Limited, Darahman Nummohaed BahRam And Merbib Dedrahaman Bahram vs Tanzania Portal Bank, Mathew Thomas Mbatta And Joseph Simbilingungwa Mwachula, Civil Application No. 133 of 2005, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO133OF2005.pdf',
'NULL'),
('Uniafrica Limited, Karim Kanji and Minaz Kanji vs Exim Bank (T) Ltd, Civil Appeal No. 30 of 2006, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO30OF2006.pdf',
'NULL'),
('Tanga Cement Co. Ltd vs Christopherson Co. Ltd, Civil Appeal No. 133 of 2006, Court of Appeal',
'http://localhost:8888/miriam_project/cases/AR133of2006(2).pdf',
'NULL'),
('Standard Chartered Bank (Tanzania) Ltd vs Bata Shoe Company (T) Limited, Civil Application No. 101 of 2006, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO101OF2006(3).pdf',
'NULL'),
('The Registered Trustees of Agricultural Inputs Trust Funds vs Alhaji Ali Utoto, Civil Application N0. 62 of 2007, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CIVNO62OF2007.pdf',
'NULL'),
('Clemence Mpondelo And Mapambano Charles vs The Republic, Criminal Appeal No. 41 of 2016, Court of Appeal',
'http://localhost:8888/miriam_project/cases/CLEMENCE-MPONDELO-AND-MAPAMBANO-VS-THE-REPUB-CRIM-APPEA-NO.41OF-2016-HON.MBAROUKJ.A.pdf',
'http://localhost:8888/miriam_project/cases/ClemenceMpondelo.pdf'),
('Emmanuel Chigoji vs The Republic, Criminal Appeal No. 63 of 2016, Court of Appeal',
'http://localhost:8888/miriam_project/cases/EMMANUEL-CHIGOJI-VS-THE-REPUB-CRIM-APPEA-NO.63-OF-2016-HON.MZIRAYJ.A.pdf',
'http://localhost:8888/miriam_project/cases/EmmanuelChigojiSummary.pdf'),
('Tano Mbika vs The Republic, Criminal Appeal No. 152 of 2016, Court of Appeal',
'http://localhost:8888/miriam_project/cases/TANO-MBIKA-VS-THE-REPUB-CRIM-APPEA-NO.152-OF-2016-HON.MZIRAYJ.A.pdf',
'http://localhost:8888/miriam_project/cases/TanoMbika.pdf'),
('Ally Rashidi vs The Republic, Criminal Appeal No. 540 of 2016, Court of Appeal',
'http://localhost:8888/miriam_project/cases/ALLY-RASHIDI-VS-THE-REPUB-CRIM-APPEA-NO.540-OF-2016-HON.MKUYEJ.A.pdf',
'http://localhost:8888/miriam_project/cases/AllyRashidiSummary.pdf');